import fs from "fs";

// This was just used to create the houseLawmakers.ts file
// It's not used in the actual analysis
// The array was scraped from https://www.theguardian.com/us-news/2021/jan/07/list-republicans-voted-to-reject-election-results

const lawmakers = [
  "Robert Aderholt (R-AL)",
  "Mike Rogers (R-AL)",
  "Mo Brooks (R-AL)",
  "Gary Palmer (R-AL)",
  "Felix Moore (R-AL)",
  "Rick Crawford (R-AR)",
  "Paul Gosar (R-AZ)",
  "Andy Biggs (R-AZ)",
  "Debbie Lesko (R-AZ)",
  "Ken Calvert (R-CA)",
  "Darrell Issa (R-CA)",
  "Devin Nunes (R-CA)",
  "Kevin McCarthy (R-CA)",
  "Doug LaMalfa (R-CA)",
  "Mike Garcia (R-CA)",
  "Jay Obernolte (R-CA)",
  "Doug Lamborn (R-CO)",
  "Lauren Boebert (R-CO)",
  "Mario Diaz-Balart (R-FL)",
  "Bill Posey (R-FL)",
  "Daniel Webster (R-FL)",
  "Matt Gaetz (R-FL)",
  "Neal Dunn (R-FL)",
  "John Rutherford (R-FL)",
  "Brian Mast (R-FL)",
  "Gregory Steube (R-FL)",
  "Katherine Cammack (R-FL)",
  "Scott Franklin (R-FL)",
  "Byron Donalds (R-FL)",
  "Carlos Giménez (R-FL)",
  "Buddy Carter (R-GA)",
  "Jody Hice (R-GA)",
  "Barry Loudermilk (R-GA)",
  "Rick Allen (R-GA)",
  "Andrew Clyde (R-GA)",
  "Marjorie Greene (R-GA)",
  "Russ Fulcher (R-ID)",
  "Mike Bost (R-IL)",
  "Mary Miller (R-IL)",
  "Jackie Walorski (R-IN)",
  "Jim Banks (R-IN)",
  "James Baird (R-IN)",
  "Ron Estes (R-KS)",
  "Tracey Mann (R-KS)",
  "Hal Rogers (R-KY)",
  "Steve Scalise (R-LA)",
  "Clay Higgins (R-LA)",
  "Mike Johnson (R-LA)",
  "Andy Harris (R-MD)",
  "Tim Walberg (R-MI)",
  "Jack Bergman (R-MI)",
  "Lisa McClain (R-MI)",
  "Jim Hagedorn (R-MN)",
  "Michelle Fischbach (R-MN)",
  "Sam Graves (R-MO)",
  "Blaine Luetkemeyer (R-MO)",
  "Vicky Hartzler (R-MO)",
  "Billy Long (R-MO)",
  "Jason Smith (R-MO)",
  "Steven Palazzo (R-MS)",
  "Trent Kelly (R-MS)",
  "Michael Guest (R-MS)",
  "Matthew Rosendale Sr. (R-MT)",
  "Richard Hudson (R-NC)",
  "David Rouzer (R-NC)",
  "Ted Budd (R-NC)",
  "Dan Bishop (R-NC)",
  "David Cawthorn (R-NC)",
  "Adrian Smith (R-NE)",
  "Jefferson Van Drew (R-NJ)",
  "Stella Herrell (R-NM)",
  "Lee Zeldin (R-NY)",
  "Chris Jacobs (R-NY)",
  "Nicole Malliotakis (R-NY)",
  "Jim Jordan (R-OH)",
  "Bill Johnson (R-OH)",
  "Bob Gibbs (R-OH)",
  "Warren Davidson (R-OH)",
  "Tom Cole (R-OK)",
  "Frank Lucas (R-OK)",
  "Markwayne Mullin (R-OK)",
  "Kevin Hern (R-OK)",
  "Stephanie Bice (R-OK)",
  "Mike Kelly (R-PA)",
  "Scott Perry (R-PA)",
  "John Joyce (R-PA)",
  "Guy Reschenthaler (R-PA)",
  "Joe Wilson (R-SC)",
  "Jeff Duncan (R-SC)",
  "Tom Rice (R-SC)",
  "William Timmons (R-SC)",
  "Chuck Fleischmann (R-TN)",
  "Scott DesJarlais (R-TN)",
  "Tim Burchett (R-TN)",
  "John Rose (R-TN)",
  "Mark Green (R-TN)",
  "Diana Harshbarger (R-TN)",
  "Michael Burgess (R-TX)",
  "John Carter (R-TX)",
  "Pete Sessions (R-TX)",
  "Randy Weber (R-TX)",
  "Roger Williams (R-TX)",
  "Brian Babin (R-TX)",
  "Jodey Arrington (R-TX)",
  "Michael Cloud (R-TX)",
  "Lance Gooden (R-TX)",
  "Ron Wright (R-TX)",
  "Patrick Fallon (R-TX)",
  "August Pfluger II (R-TX)",
  "Ronny Jackson (R-TX)",
  "Troy Nehls (R-TX)",
  "Morgan Griffith (R-VA)",
  "Ben Cline (R-VA)",
  "Robert Good (R-VA)",
  "Thomas Tiffany (R-WI)",
  "Scott Fitzgerald (R-WI)",
  "Carol Miller (R-WV)",
  "David Schweikert (R-AZ)",
  "Greg Pence (R-IN)",
  "Jacob LaTurner (R-KS)",
  "Garret Graves (R-LA)",
  "Virginia Foxx (R-NC)",
  "Gregory Murphy (R-NC)",
  "Elise Stefanik (R-NY)",
  "Steve Chabot (R-OH)",
  "Cliff Bentz (R-OR)",
  "Glenn Thompson (R-PA)",
  "Lloyd Smucker (R-PA)",
  "Daniel Meuser (R-PA)",
  "Fred Keller (R-PA)",
  "David Kustoff (R-TN)",
  "Beth Van Duyne (R-TX)",
  "Chris Stewart (R-UT)",
  "Clarence Owens (R-UT)",
  "Robert Wittman (R-VA)",
  "Alex Mooney (R-WV)",
  "Jerry Carl (R-AL)",
  "Ralph Norman (R-SC)",
  "Louie Gohmert (R-TX)",
];

type Lawmaker = {
  first: string;
  last: string;
  state: string;
  billCount: number;
  gop: number;
  indie: number;
  dem: number;
};

const res: Lawmaker[] = lawmakers.map((lawmaker) => {
  const info = lawmaker.split(" ");
  const first = info[0];
  const last = info[1];
  const state = info[2].slice(3, 5);
  return { first, last, state, billCount: 0, gop: 0, indie: 0, dem: 0 };
});

fs.writeFileSync(
  "./houseLawmakers.json",
  JSON.stringify(res, null, 2),
  "utf-8"
);
