export const senateLawmakers = [
  {
    first: "Ted",
    last: "Cruz",
    state: "TX",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Ron",
    last: "Johnson",
    state: "WI",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "John",
    last: "Kennedy",
    state: "LA",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "James",
    last: "Lankford",
    state: "OK",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Josh",
    last: "Hawley",
    state: "MO",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Cindy",
    last: "Hyde-Smith",
    state: "MS",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  //Lummis,+Cynthia+M.+[R-WY]"
  //`https://congress.gov/search?searchResultViewType=expanded&q={"source":"legislation","congress":"117","senate-sponsor":"${last},+${first+M.}+[R-${state}]"}`;
  {
    first: "Cynthia",
    last: "Lummis",
    state: "WY",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Roger",
    last: "Marshall",
    state: "KS",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Rick",
    last: "Scott",
    state: "FL",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Tommy",
    last: "Tuberville",
    state: "AL",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Marsha",
    last: "Blackburn",
    state: "TN",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Mike",
    last: "Braun",
    state: "IN",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Steve",
    last: "Daines",
    state: "MT",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
  {
    first: "Bill",
    last: "Hagerty",
    state: "TN",
    billCount: 0,
    gop: 0,
    dem: 0,
    indie: 0,
  },
];

//export const senateLawmakers = [
//{
//first: "Ted",
//last: "Cruz",
//state: "TX",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Ron",
//last: "Johnson",
//state: "WI",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "John",
//last: "Kennedy",
//state: "LA",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "James",
//last: "Lankford",
//state: "OK",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Josh+",
//last: "Hawley",
//state: "MO",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Cindy",
//last: "Hyde-Smith",
//state: "MS",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
////Lummis,+Cynthia+M.+[R-WY]"
////`https://congress.gov/search?searchResultViewType=expanded&q={"source":"legislation","congress":"117","senate-sponsor":"${last},+${first+M.}+[R-${state}]"}`;
//{
//first: "Cynthia+M.",
//last: "Lummis",
//state: "WY",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Roger+W.",
//last: "Marshall",
//state: "KS",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Rick+",
//last: "Scott",
//state: "FL",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Tommy",
//last: "Tuberville",
//state: "AL",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Marsha",
//last: "Blackburn",
//state: "TN",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Mike+",
//last: "Braun",
//state: "IN",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Steve",
//last: "Daines",
//state: "MT",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//{
//first: "Bill",
//last: "Hagerty",
//state: "TN",
//billCount: 0,
//gop: 0,
//dem: 0,
//indie: 0,
//},
//];
